version: "3.9"
services:
  nodejs:
    build: .
    container_name: nodejs
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

    command: "npm start"

